### ISSUE TITLE
Can't install module

### ISSUE THREAD

**Issue by TheMorningStarLucifer** [wickercar/foundry-ai-text-importer#3]
I get this error when I try to install the module.

![image](https://github.com/wickercar/foundry-ai-text-importer/assets/137843163/f9f59849-08a9-4563-9239-689051338116)
****

**Comment by jrbuda** [comment]
Similar on my end. Wanted to test something with it and could not get it to install. Same error
![image](https://github.com/wickercar/foundry-ai-text-importer/assets/47678481/d1509c3c-eb8c-4c28-970e-4b0ee205dea8)

**Comment by jrbuda** [comment]
I tried both the installer GUI and the manifest link

**Comment by wickercar** [comment]
Fix is live, thanks a lot for the callout! 

Not sure why this didn't show up in my local dev version but I've verified the fix after downloading from the installer GUI. Check out v1.0.9 (latest) on the installer GUI.

**Comment by wickercar** [comment]
Closing since fix is live in 1.0.9
